import os


class ConstantesExercicio5:

    SEPARADOR_DE_PASTAS = os.sep
    QUEBRA_DE_LINHA = "\n"

    PASTA_DA_PARTE_1 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    PASTA_DOS_GRAFICOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "graficos"
    PASTA_DOS_RESULTADOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "resultados"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_STEEPEST_DESCENT = "exercicio_5_funcao_objetivo_steepest_descent.png"
    NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_STEEPEST_DESCENT = "exercicio_5_norma_gradiente_steepest_descent.png"
    NOME_DO_GRAFICO_DAS_COORDENADAS_DO_STEEPEST_DESCENT = "exercicio_5_coordenadas_steepest_descent.png"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NEWTON = "exercicio_5_funcao_objetivo_newton.png"
    NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NEWTON = "exercicio_5_norma_gradiente_newton.png"
    NOME_DO_GRAFICO_DAS_COORDENADAS_DO_NEWTON = "exercicio_5_coordenadas_newton.png"

    NOME_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = "exercicio_5_comparacao_funcao_objetivo.png"
    NOME_DO_GRAFICO_COMPARATIVO_DA_NORMA_DO_GRADIENTE = "exercicio_5_comparacao_norma_gradiente.png"

    NOME_DO_ARQUIVO_DO_RESULTADO_DO_STEEPEST_DESCENT = "exercicio_5_resultado_steepest_descent.txt"
    NOME_DO_ARQUIVO_DO_RESULTADO_DO_NEWTON = "exercicio_5_resultado_newton.txt"
    NOME_DO_ARQUIVO_DA_COMPARACAO = "exercicio_5_comparacao.txt"

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_STEEPEST_DESCENT = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_STEEPEST_DESCENT
    CAMINHO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_STEEPEST_DESCENT = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_STEEPEST_DESCENT
    CAMINHO_DO_GRAFICO_DAS_COORDENADAS_DO_STEEPEST_DESCENT = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DAS_COORDENADAS_DO_STEEPEST_DESCENT

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NEWTON = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NEWTON
    CAMINHO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NEWTON = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NEWTON
    CAMINHO_DO_GRAFICO_DAS_COORDENADAS_DO_NEWTON = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DAS_COORDENADAS_DO_NEWTON

    CAMINHO_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO
    CAMINHO_DO_GRAFICO_COMPARATIVO_DA_NORMA_DO_GRADIENTE = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_COMPARATIVO_DA_NORMA_DO_GRADIENTE

    CAMINHO_DO_ARQUIVO_DO_RESULTADO_DO_STEEPEST_DESCENT = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DO_RESULTADO_DO_STEEPEST_DESCENT
    CAMINHO_DO_ARQUIVO_DO_RESULTADO_DO_NEWTON = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DO_RESULTADO_DO_NEWTON
    CAMINHO_DO_ARQUIVO_DA_COMPARACAO = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DA_COMPARACAO

    NOME_DO_METODO_STEEPEST_DESCENT = "Steepest Descent com busca linear exata"
    NOME_DO_METODO_NEWTON = "Método de Newton"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_STEEPEST_DESCENT = "Exercício 5 - Função objetivo do Steepest Descent"
    TITULO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_STEEPEST_DESCENT = "Exercício 5 - Norma do gradiente do Steepest Descent"
    TITULO_DO_GRAFICO_DAS_COORDENADAS_DO_STEEPEST_DESCENT = "Exercício 5 - Trajetória das coordenadas do Steepest Descent"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NEWTON = "Exercício 5 - Função objetivo do Newton"
    TITULO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NEWTON = "Exercício 5 - Norma do gradiente do Newton"
    TITULO_DO_GRAFICO_DAS_COORDENADAS_DO_NEWTON = "Exercício 5 - Trajetória das coordenadas do Newton"

    TITULO_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = "Exercício 5 - Comparação da função objetivo"
    TITULO_DO_GRAFICO_COMPARATIVO_DA_NORMA_DO_GRADIENTE = "Exercício 5 - Comparação da norma do gradiente"

    TEXTO_DO_EIXO_DAS_ITERACOES = "Iteração"
    TEXTO_DO_EIXO_DA_FUNCAO_OBJETIVO = "Função objetivo"
    TEXTO_DO_EIXO_DA_NORMA_DO_GRADIENTE = "Norma do gradiente"
    TEXTO_DO_EIXO_DAS_COORDENADAS = "Valor da coordenada"

    MODO_DE_ESCRITA = "w"
    CODIFICACAO_DOS_ARQUIVOS_DE_SAIDA = "utf-8"

    QUANTIDADE_NULA = 0
    INDICE_INICIAL = 0
    INCREMENTO_UNITARIO = 1