import os


class ConstantesParte2:

    SEPARADOR_DE_PASTAS = os.sep
    QUEBRA_DE_LINHA = "\n"

    PASTA_DA_PARTE_1 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    PASTA_DOS_GRAFICOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "graficos"
    PASTA_DOS_RESULTADOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "resultados"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_STEEPEST_DESCENT = "parte_2_funcao_objetivo_steepest_descent.png"
    NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_STEEPEST_DESCENT = "parte_2_norma_gradiente_steepest_descent.png"
    NOME_DO_GRAFICO_DA_TRAJETORIA_DO_STEEPEST_DESCENT = "parte_2_trajetoria_steepest_descent.png"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NEWTON = "parte_2_funcao_objetivo_newton.png"
    NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NEWTON = "parte_2_norma_gradiente_newton.png"
    NOME_DO_GRAFICO_DA_TRAJETORIA_DO_NEWTON = "parte_2_trajetoria_newton.png"

    NOME_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = "parte_2_comparacao_funcao_objetivo.png"
    NOME_DO_GRAFICO_COMPARATIVO_DA_NORMA_DO_GRADIENTE = "parte_2_comparacao_norma_gradiente.png"

    NOME_DO_ARQUIVO_DE_RESULTADOS_DO_STEEPEST_DESCENT = "parte_2_resultado_steepest_descent.txt"
    NOME_DO_ARQUIVO_DE_RESULTADOS_DO_NEWTON = "parte_2_resultado_newton.txt"
    NOME_DO_ARQUIVO_COMPARATIVO = "parte_2_comparacao.txt"

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_STEEPEST_DESCENT = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_STEEPEST_DESCENT
    CAMINHO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_STEEPEST_DESCENT = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_STEEPEST_DESCENT
    CAMINHO_DO_GRAFICO_DA_TRAJETORIA_DO_STEEPEST_DESCENT = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_TRAJETORIA_DO_STEEPEST_DESCENT

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NEWTON = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NEWTON
    CAMINHO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NEWTON = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NEWTON
    CAMINHO_DO_GRAFICO_DA_TRAJETORIA_DO_NEWTON = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_TRAJETORIA_DO_NEWTON

    CAMINHO_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO
    CAMINHO_DO_GRAFICO_COMPARATIVO_DA_NORMA_DO_GRADIENTE = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_COMPARATIVO_DA_NORMA_DO_GRADIENTE

    CAMINHO_DO_ARQUIVO_DE_RESULTADOS_DO_STEEPEST_DESCENT = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_RESULTADOS_DO_STEEPEST_DESCENT
    CAMINHO_DO_ARQUIVO_DE_RESULTADOS_DO_NEWTON = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_RESULTADOS_DO_NEWTON
    CAMINHO_DO_ARQUIVO_COMPARATIVO = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_COMPARATIVO

    NOME_DO_METODO_STEEPEST_DESCENT = "Steepest Descent com busca linear exata"
    NOME_DO_METODO_NEWTON = "Método de Newton"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_STEEPEST_DESCENT = "Função objetivo - Steepest Descent"
    TITULO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_STEEPEST_DESCENT = "Norma do gradiente - Steepest Descent"
    TITULO_DO_GRAFICO_DA_TRAJETORIA_DO_STEEPEST_DESCENT = "Trajetória - Steepest Descent"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NEWTON = "Função objetivo - Newton"
    TITULO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NEWTON = "Norma do gradiente - Newton"
    TITULO_DO_GRAFICO_DA_TRAJETORIA_DO_NEWTON = "Trajetória - Newton"

    TITULO_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = "Comparação da função objetivo"
    TITULO_DO_GRAFICO_COMPARATIVO_DA_NORMA_DO_GRADIENTE = "Comparação da norma do gradiente"

    TEXTO_DO_EIXO_DAS_ITERACOES = "Iteração"
    TEXTO_DO_EIXO_DA_FUNCAO_OBJETIVO = "Função objetivo"
    TEXTO_DO_EIXO_DA_NORMA_DO_GRADIENTE = "Norma do gradiente"
    TEXTO_DO_EIXO_X_1 = "x1"
    TEXTO_DO_EIXO_X_2 = "x2"

    TOLERANCIA_PADRAO = 1.0e-8
    TOLERANCIA_NUMERICA = 1.0e-12
    NUMERO_MAXIMO_DE_ITERACOES_PADRAO = 1000

    QUANTIDADE_NULA = 0
    QUANTIDADE_DE_VARIAVEIS_PARA_GRAFICO_DE_TRAJETORIA = 2
    INDICE_INICIAL = 0
    INDICE_DA_SEGUNDA_VARIAVEL = 1
    INCREMENTO_UNITARIO = 1

    QUANTIDADE_DE_PONTOS_DO_CONTORNO = 150
    MARGEM_DO_GRAFICO_DE_TRAJETORIA = 1.0
    QUANTIDADE_DE_NIVEIS_DO_CONTORNO = 30

    MODO_DE_ESCRITA = "w"
    CODIFICACAO_DOS_ARQUIVOS_DE_SAIDA = "utf-8"

    MOTIVO_DA_PARADA_POR_NORMA_DO_GRADIENTE = "Norma do gradiente menor ou igual à tolerância."
    MOTIVO_DA_PARADA_POR_NUMERO_MAXIMO_DE_ITERACOES = "Número máximo de iterações atingido."
    MOTIVO_DA_PARADA_POR_DIRECAO_INVALIDA = "Não foi possível determinar uma direção de descida válida."

    MENSAGEM_DE_ERRO_DA_PARTE_2 = "Não foi possível executar a Parte 2."
    MENSAGEM_DE_SUCESSO_DA_PARTE_2 = "Parte 2 executada com sucesso."