import os


class Constantes:

    SEPARADOR_DE_PASTAS = os.sep
    TEXTO_VAZIO = ""
    DELIMITADOR_CSV = ","
    QUEBRA_DE_LINHA = "\n"

    PASTA_DA_PARTE_1 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    PASTA_DOS_DADOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "dados"
    PASTA_DOS_DADOS_ORIGINAIS = PASTA_DOS_DADOS + SEPARADOR_DE_PASTAS + "originais"
    PASTA_DOS_DADOS_PROCESSADOS = PASTA_DOS_DADOS + SEPARADOR_DE_PASTAS + "processados"
    PASTA_DOS_GRAFICOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "graficos"
    PASTA_DOS_RESULTADOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "resultados"

    NOME_DO_ARQUIVO_DATATRAINING = "datatraining.txt"
    NOME_DO_ARQUIVO_DATATEST = "datatest.txt"
    NOME_DO_ARQUIVO_DATATEST_2 = "datatest2.txt"

    NOME_DO_ARQUIVO_DE_TREINAMENTO_PROCESSADO = "treinamento_80.csv"
    NOME_DO_ARQUIVO_DE_TESTE_PROCESSADO = "teste_20.csv"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO = "funcao_objetivo_steepest_descent.png"
    NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE = "norma_gradiente_steepest_descent.png"
    NOME_DO_GRAFICO_DA_ACURACIA = "acuracia_steepest_descent.png"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_SGD = "funcao_objetivo_sgd.png"
    NOME_DO_GRAFICO_DA_ACURACIA_DO_SGD = "acuracia_sgd.png"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_MOMENTUM = "funcao_objetivo_momentum.png"
    NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_MOMENTUM = "norma_gradiente_momentum.png"
    NOME_DO_GRAFICO_DA_ACURACIA_DO_MOMENTUM = "acuracia_momentum.png"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NESTEROV = "funcao_objetivo_nesterov.png"
    NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NESTEROV = "norma_gradiente_nesterov.png"
    NOME_DO_GRAFICO_DA_ACURACIA_DO_NESTEROV = "acuracia_nesterov.png"

    NOME_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = "comparacao_funcao_objetivo.png"
    NOME_DO_GRAFICO_COMPARATIVO_DA_ACURACIA = "comparacao_acuracia.png"
    NOME_DO_GRAFICO_DOS_LEARNING_RATES = "comparacao_learning_rates.png"
    NOME_DO_GRAFICO_DOS_MINI_BATCHES = "comparacao_mini_batches.png"
    NOME_DO_GRAFICO_DOS_BETAS_DO_MOMENTUM = "comparacao_betas_momentum.png"
    NOME_DO_GRAFICO_DOS_BETAS_DO_NESTEROV = "comparacao_betas_nesterov.png"

    NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_1 = "resultado_exercicio_1.txt"
    NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_2 = "resultado_exercicio_2.txt"
    NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_3 = "resultado_exercicio_3.txt"
    NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_4 = "resultado_exercicio_4.txt"

    NOME_DO_ARQUIVO_DA_TABELA_COMPARATIVA = "comparacao_metodos.csv"
    NOME_DO_ARQUIVO_DA_TABELA_DE_LEARNING_RATES = "comparacao_learning_rates.csv"
    NOME_DO_ARQUIVO_DA_TABELA_DE_MINI_BATCHES = "comparacao_mini_batches.csv"
    NOME_DO_ARQUIVO_DA_TABELA_DE_BETAS = "comparacao_betas.csv"
    NOME_DO_ARQUIVO_DO_RESUMO_DA_PARTE_1 = "resumo_parte_1.txt"

    CAMINHO_DO_ARQUIVO_DATATRAINING = PASTA_DOS_DADOS_ORIGINAIS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DATATRAINING
    CAMINHO_DO_ARQUIVO_DATATEST = PASTA_DOS_DADOS_ORIGINAIS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DATATEST
    CAMINHO_DO_ARQUIVO_DATATEST_2 = PASTA_DOS_DADOS_ORIGINAIS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DATATEST_2

    CAMINHO_DO_ARQUIVO_DE_TREINAMENTO_PROCESSADO = PASTA_DOS_DADOS_PROCESSADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_TREINAMENTO_PROCESSADO
    CAMINHO_DO_ARQUIVO_DE_TESTE_PROCESSADO = PASTA_DOS_DADOS_PROCESSADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_TESTE_PROCESSADO

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO
    CAMINHO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE
    CAMINHO_DO_GRAFICO_DA_ACURACIA = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_ACURACIA

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_SGD = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_SGD
    CAMINHO_DO_GRAFICO_DA_ACURACIA_DO_SGD = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_ACURACIA_DO_SGD

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_MOMENTUM = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_MOMENTUM
    CAMINHO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_MOMENTUM = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_MOMENTUM
    CAMINHO_DO_GRAFICO_DA_ACURACIA_DO_MOMENTUM = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_ACURACIA_DO_MOMENTUM

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NESTEROV = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NESTEROV
    CAMINHO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NESTEROV = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NESTEROV
    CAMINHO_DO_GRAFICO_DA_ACURACIA_DO_NESTEROV = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_ACURACIA_DO_NESTEROV

    CAMINHO_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO
    CAMINHO_DO_GRAFICO_COMPARATIVO_DA_ACURACIA = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_COMPARATIVO_DA_ACURACIA
    CAMINHO_DO_GRAFICO_DOS_LEARNING_RATES = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DOS_LEARNING_RATES
    CAMINHO_DO_GRAFICO_DOS_MINI_BATCHES = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DOS_MINI_BATCHES
    CAMINHO_DO_GRAFICO_DOS_BETAS_DO_MOMENTUM = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DOS_BETAS_DO_MOMENTUM
    CAMINHO_DO_GRAFICO_DOS_BETAS_DO_NESTEROV = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DOS_BETAS_DO_NESTEROV

    CAMINHO_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_1 = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_1
    CAMINHO_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_2 = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_2
    CAMINHO_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_3 = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_3
    CAMINHO_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_4 = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_4

    CAMINHO_DO_ARQUIVO_DA_TABELA_COMPARATIVA = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DA_TABELA_COMPARATIVA
    CAMINHO_DO_ARQUIVO_DA_TABELA_DE_LEARNING_RATES = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DA_TABELA_DE_LEARNING_RATES
    CAMINHO_DO_ARQUIVO_DA_TABELA_DE_MINI_BATCHES = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DA_TABELA_DE_MINI_BATCHES
    CAMINHO_DO_ARQUIVO_DA_TABELA_DE_BETAS = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DA_TABELA_DE_BETAS
    CAMINHO_DO_ARQUIVO_DO_RESUMO_DA_PARTE_1 = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DO_RESUMO_DA_PARTE_1

    listaDeCaminhosDosArquivosOriginais = [
        CAMINHO_DO_ARQUIVO_DATATRAINING,
        CAMINHO_DO_ARQUIVO_DATATEST,
        CAMINHO_DO_ARQUIVO_DATATEST_2
    ]

    listaDeCabecalhoOriginal = [
        "date",
        "Temperature",
        "Humidity",
        "Light",
        "CO2",
        "HumidityRatio",
        "Occupancy"
    ]

    listaDeCabecalhoProcessado = [
        "id",
        "date",
        "Temperature",
        "Humidity",
        "Light",
        "CO2",
        "HumidityRatio",
        "Occupancy"
    ]

    listaDeLearningRatesDosExperimentos = [0.01, 0.05, 0.1]
    listaDeTamanhosDosMiniBatches = [16, 32, 64]
    listaDeBetasDosExperimentos = [0.5, 0.9, 0.99]

    PROPORCAO_DE_TREINAMENTO = 0.80
    PROPORCAO_DE_TESTE = 1.00 - PROPORCAO_DE_TREINAMENTO

    LEARNING_RATE_PADRAO = 0.1
    TOLERANCIA_PADRAO = 1.0e-6
    NUMERO_MAXIMO_DE_ITERACOES_PADRAO = 1000
    NUMERO_MAXIMO_DE_ITERACOES_DO_SGD = 100
    NUMERO_MAXIMO_DE_ITERACOES_DO_MOMENTUM = 1000
    NUMERO_MAXIMO_DE_ITERACOES_DO_NESTEROV = 1000
    NUMERO_MAXIMO_DE_ITERACOES_DOS_EXPERIMENTOS = 300
    NUMERO_MAXIMO_DE_EPOCAS_DOS_EXPERIMENTOS_DO_SGD = 50

    TAMANHO_DO_MINI_BATCH_PADRAO = 32
    BETA_PADRAO = 0.9
    EMBARALHAR_AMOSTRAS_POR_PADRAO = True
    VALOR_INICIAL_DOS_PARAMETROS = 0.0
    LIMIAR_DE_CLASSIFICACAO = 0.5

    METADE = 0.5
    TOLERANCIA_NUMERICA = 1.0e-12

    MENOR_PROBABILIDADE_PERMITIDA = 1.0e-15
    MAIOR_PROBABILIDADE_PERMITIDA = 1.0 - MENOR_PROBABILIDADE_PERMITIDA

    QUANTIDADE_NULA = 0
    QUANTIDADE_MINIMA_DE_AMOSTRAS = 2
    QUANTIDADE_MINIMA_DE_LINHAS_DO_ARQUIVO = 2

    QUANTIDADE_DE_COLUNAS_DO_CABECALHO_ORIGINAL = 7
    QUANTIDADE_DE_COLUNAS_DA_LINHA_ORIGINAL = 8
    QUANTIDADE_DE_COLUNAS_DO_CABECALHO_PROCESSADO = 8
    QUANTIDADE_DE_COLUNAS_DA_LINHA_PROCESSADA = 8

    QUANTIDADE_DE_DIMENSOES_DO_VETOR = 1
    QUANTIDADE_DE_DIMENSOES_DA_MATRIZ = 2

    INDICE_INICIAL = 0
    INCREMENTO_UNITARIO = 1
    PRIMEIRO_IDENTIFICADOR = 1

    INDICE_DO_CABECALHO = 0
    INDICE_DA_PRIMEIRA_LINHA_DE_DADOS = 1

    INDICE_DA_QUANTIDADE_DE_LINHAS = 0
    INDICE_DA_QUANTIDADE_DE_COLUNAS = 1

    INDICE_DAS_ENTRADAS_DO_MINI_BATCH = 0
    INDICE_DAS_SAIDAS_DO_MINI_BATCH = 1

    INDICE_DAS_ENTRADAS_DE_TREINAMENTO = 0
    INDICE_DAS_SAIDAS_DE_TREINAMENTO = 1
    INDICE_DAS_ENTRADAS_DE_TESTE = 2
    INDICE_DAS_SAIDAS_DE_TESTE = 3

    INDICE_DO_IDENTIFICADOR_NA_LINHA_ORIGINAL = 0
    INDICE_DA_DATA_NA_LINHA_ORIGINAL = 1
    INDICE_DA_TEMPERATURA_NA_LINHA_ORIGINAL = 2
    INDICE_DA_UMIDADE_NA_LINHA_ORIGINAL = 3
    INDICE_DA_LUMINOSIDADE_NA_LINHA_ORIGINAL = 4
    INDICE_DO_CO2_NA_LINHA_ORIGINAL = 5
    INDICE_DA_RAZAO_DE_UMIDADE_NA_LINHA_ORIGINAL = 6
    INDICE_DA_OCUPACAO_NA_LINHA_ORIGINAL = 7

    INDICE_DO_NOME_DO_METODO_NO_RESULTADO = 0
    INDICE_DO_LEARNING_RATE_NO_RESULTADO = 1
    INDICE_DO_MINI_BATCH_NO_RESULTADO = 2
    INDICE_DO_BETA_NO_RESULTADO = 3
    INDICE_DAS_ITERACOES_NO_RESULTADO = 4
    INDICE_DO_TEMPO_NO_RESULTADO = 5
    INDICE_DA_FUNCAO_OBJETIVO_FINAL_NO_RESULTADO = 6
    INDICE_DA_ACURACIA_DE_TREINAMENTO_NO_RESULTADO = 7
    INDICE_DA_ACURACIA_DE_TESTE_NO_RESULTADO = 8
    INDICE_DO_RESULTADO_DO_TREINAMENTO = 9

    OCUPACAO_VAZIA = 0
    OCUPACAO_PRESENTE = 1

    FORMATO_DA_DATA = "%Y-%m-%d %H:%M:%S"

    CODIFICACAO_DOS_ARQUIVOS_DE_ENTRADA = "utf-8-sig"
    CODIFICACAO_DOS_ARQUIVOS_DE_SAIDA = "utf-8"

    MODO_DE_LEITURA = "r"
    MODO_DE_ESCRITA = "w"

    SEMENTE_ALEATORIA = 42

    NOME_DO_METODO_STEEPEST_DESCENT = "Steepest Descent"
    NOME_DO_METODO_SGD = "SGD"
    NOME_DO_METODO_MOMENTUM = "Momentum"
    NOME_DO_METODO_NESTEROV = "Nesterov"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO = "Curva da função objetivo"
    TITULO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE = "Evolução da norma do gradiente"
    TITULO_DO_GRAFICO_DA_ACURACIA = "Evolução da acurácia de treinamento"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_SGD = "Curva da função objetivo do SGD"
    TITULO_DO_GRAFICO_DA_ACURACIA_DO_SGD = "Evolução da acurácia do SGD"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_MOMENTUM = "Curva da função objetivo do Momentum"
    TITULO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_MOMENTUM = "Evolução da norma do gradiente do Momentum"
    TITULO_DO_GRAFICO_DA_ACURACIA_DO_MOMENTUM = "Evolução da acurácia do Momentum"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO_DO_NESTEROV = "Curva da função objetivo do Nesterov"
    TITULO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE_DO_NESTEROV = "Evolução da norma do gradiente do Nesterov"
    TITULO_DO_GRAFICO_DA_ACURACIA_DO_NESTEROV = "Evolução da acurácia do Nesterov"

    TITULO_DO_GRAFICO_COMPARATIVO_DA_FUNCAO_OBJETIVO = "Comparação da função objetivo"
    TITULO_DO_GRAFICO_COMPARATIVO_DA_ACURACIA = "Comparação da acurácia"
    TITULO_DO_GRAFICO_DOS_LEARNING_RATES = "Influência do learning rate no Steepest Descent"
    TITULO_DO_GRAFICO_DOS_MINI_BATCHES = "Efeito do tamanho do mini-batch"
    TITULO_DO_GRAFICO_DOS_BETAS_DO_MOMENTUM = "Efeito de beta no Momentum"
    TITULO_DO_GRAFICO_DOS_BETAS_DO_NESTEROV = "Efeito de beta no Nesterov"

    TEXTO_DO_EIXO_DAS_ITERACOES = "Iteração"
    TEXTO_DO_EIXO_DAS_EPOCAS = "Época"
    TEXTO_DO_EIXO_DA_FUNCAO_OBJETIVO = "Função objetivo"
    TEXTO_DO_EIXO_DA_NORMA_DO_GRADIENTE = "Norma do gradiente"
    TEXTO_DO_EIXO_DA_ACURACIA = "Acurácia"

    CABECALHO_DA_TABELA_COMPARATIVA = "metodo,learning_rate,mini_batch,beta,iteracoes,tempo,funcao_objetivo_final,acuracia_treinamento,acuracia_teste"

    MOTIVO_DA_PARADA_POR_NORMA_DO_GRADIENTE = "Norma do gradiente menor ou igual à tolerância."
    MOTIVO_DA_PARADA_POR_VARIACAO_DA_FUNCAO_OBJETIVO = "Variação da função objetivo menor ou igual à tolerância."
    MOTIVO_DA_PARADA_POR_NUMERO_MAXIMO_DE_ITERACOES = "Número máximo de iterações atingido."

    MENSAGEM_DE_ERRO_DE_PROCESSAMENTO = "Não foi possível processar os arquivos."
    MENSAGEM_DE_ERRO_DO_EXERCICIO_1 = "Não foi possível executar o Exercício 1."
    MENSAGEM_DE_ERRO_DO_EXERCICIO_2 = "Não foi possível executar o Exercício 2."
    MENSAGEM_DE_ERRO_DO_EXERCICIO_3 = "Não foi possível executar o Exercício 3."
    MENSAGEM_DE_ERRO_DO_EXERCICIO_4 = "Não foi possível executar o Exercício 4."
    MENSAGEM_DE_ERRO_DOS_EXPERIMENTOS = "Não foi possível executar os experimentos da Parte 1."

    MENSAGEM_DE_SUCESSO_DO_EXERCICIO_1 = "Exercício 1 executado com sucesso."
    MENSAGEM_DE_SUCESSO_DO_EXERCICIO_2 = "Exercício 2 executado com sucesso."
    MENSAGEM_DE_SUCESSO_DO_EXERCICIO_3 = "Exercício 3 executado com sucesso."
    MENSAGEM_DE_SUCESSO_DO_EXERCICIO_4 = "Exercício 4 executado com sucesso."
    MENSAGEM_DE_SUCESSO_DOS_EXPERIMENTOS = "Experimentos comparativos da Parte 1 executados com sucesso."