import os


class Constantes:

    SEPARADOR_DE_PASTAS = os.sep
    TEXTO_VAZIO = ""
    DELIMITADOR_CSV = ","

    PASTA_DA_PARTE_1 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    PASTA_DOS_DADOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "dados"
    PASTA_DOS_DADOS_ORIGINAIS = PASTA_DOS_DADOS + SEPARADOR_DE_PASTAS + "originais"
    PASTA_DOS_DADOS_PROCESSADOS = PASTA_DOS_DADOS + SEPARADOR_DE_PASTAS + "processados"
    PASTA_DOS_GRAFICOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "graficos"
    PASTA_DOS_RESULTADOS = PASTA_DA_PARTE_1 + SEPARADOR_DE_PASTAS + "resultados"

    NOME_DO_ARQUIVO_DATATRAINING = "datatraining.txt"
    NOME_DO_ARQUIVO_DATATEST = "datatest.txt"
    NOME_DO_ARQUIVO_DATATEST_2 = "datatest2.txt"

    NOME_DO_ARQUIVO_DE_TREINAMENTO_PROCESSADO = "treinamento_80.csv"
    NOME_DO_ARQUIVO_DE_TESTE_PROCESSADO = "teste_20.csv"

    NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO = "funcao_objetivo_steepest_descent.png"
    NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE = "norma_gradiente_steepest_descent.png"
    NOME_DO_GRAFICO_DA_ACURACIA = "acuracia_steepest_descent.png"
    NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_1 = "resultado_exercicio_1.txt"

    CAMINHO_DO_ARQUIVO_DATATRAINING = PASTA_DOS_DADOS_ORIGINAIS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DATATRAINING
    CAMINHO_DO_ARQUIVO_DATATEST = PASTA_DOS_DADOS_ORIGINAIS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DATATEST
    CAMINHO_DO_ARQUIVO_DATATEST_2 = PASTA_DOS_DADOS_ORIGINAIS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DATATEST_2

    CAMINHO_DO_ARQUIVO_DE_TREINAMENTO_PROCESSADO = PASTA_DOS_DADOS_PROCESSADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_TREINAMENTO_PROCESSADO
    CAMINHO_DO_ARQUIVO_DE_TESTE_PROCESSADO = PASTA_DOS_DADOS_PROCESSADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_TESTE_PROCESSADO

    CAMINHO_DO_GRAFICO_DA_FUNCAO_OBJETIVO = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_FUNCAO_OBJETIVO
    CAMINHO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_NORMA_DO_GRADIENTE
    CAMINHO_DO_GRAFICO_DA_ACURACIA = PASTA_DOS_GRAFICOS + SEPARADOR_DE_PASTAS + NOME_DO_GRAFICO_DA_ACURACIA
    CAMINHO_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_1 = PASTA_DOS_RESULTADOS + SEPARADOR_DE_PASTAS + NOME_DO_ARQUIVO_DE_RESULTADOS_DO_EXERCICIO_1

    listaDeCaminhosDosArquivosOriginais = [
        CAMINHO_DO_ARQUIVO_DATATRAINING,
        CAMINHO_DO_ARQUIVO_DATATEST,
        CAMINHO_DO_ARQUIVO_DATATEST_2
    ]

    listaDeCabecalhoOriginal = [
        "date",
        "Temperature",
        "Humidity",
        "Light",
        "CO2",
        "HumidityRatio",
        "Occupancy"
    ]

    listaDeCabecalhoProcessado = [
        "id",
        "date",
        "Temperature",
        "Humidity",
        "Light",
        "CO2",
        "HumidityRatio",
        "Occupancy"
    ]

    PROPORCAO_DE_TREINAMENTO = 0.80
    PROPORCAO_DE_TESTE = 1.00 - PROPORCAO_DE_TREINAMENTO

    LEARNING_RATE_PADRAO = 0.1
    TOLERANCIA_PADRAO = 1.0e-6
    NUMERO_MAXIMO_DE_ITERACOES_PADRAO = 1000
    TAMANHO_DO_MINI_BATCH_PADRAO = 32
    BETA_PADRAO = 0.9
    EMBARALHAR_AMOSTRAS_POR_PADRAO = True
    VALOR_INICIAL_DOS_PARAMETROS = 0.0
    LIMIAR_DE_CLASSIFICACAO = 0.5

    MENOR_PROBABILIDADE_PERMITIDA = 1.0e-15
    MAIOR_PROBABILIDADE_PERMITIDA = 1.0 - MENOR_PROBABILIDADE_PERMITIDA

    QUANTIDADE_NULA = 0
    QUANTIDADE_MINIMA_DE_AMOSTRAS = 2
    QUANTIDADE_MINIMA_DE_LINHAS_DO_ARQUIVO = 2

    QUANTIDADE_DE_COLUNAS_DO_CABECALHO_ORIGINAL = 7
    QUANTIDADE_DE_COLUNAS_DA_LINHA_ORIGINAL = 8
    QUANTIDADE_DE_COLUNAS_DO_CABECALHO_PROCESSADO = 8
    QUANTIDADE_DE_COLUNAS_DA_LINHA_PROCESSADA = 8

    INDICE_INICIAL = 0
    INCREMENTO_UNITARIO = 1
    PRIMEIRO_IDENTIFICADOR = 1

    INDICE_DO_CABECALHO = 0
    INDICE_DA_PRIMEIRA_LINHA_DE_DADOS = 1

    INDICE_DO_IDENTIFICADOR_NA_LINHA_ORIGINAL = 0
    INDICE_DA_DATA_NA_LINHA_ORIGINAL = 1
    INDICE_DA_TEMPERATURA_NA_LINHA_ORIGINAL = 2
    INDICE_DA_UMIDADE_NA_LINHA_ORIGINAL = 3
    INDICE_DA_LUMINOSIDADE_NA_LINHA_ORIGINAL = 4
    INDICE_DO_CO2_NA_LINHA_ORIGINAL = 5
    INDICE_DA_RAZAO_DE_UMIDADE_NA_LINHA_ORIGINAL = 6
    INDICE_DA_OCUPACAO_NA_LINHA_ORIGINAL = 7

    OCUPACAO_VAZIA = 0
    OCUPACAO_PRESENTE = 1

    FORMATO_DA_DATA = "%Y-%m-%d %H:%M:%S"

    CODIFICACAO_DOS_ARQUIVOS_DE_ENTRADA = "utf-8-sig"
    CODIFICACAO_DOS_ARQUIVOS_DE_SAIDA = "utf-8"

    MODO_DE_LEITURA = "r"
    MODO_DE_ESCRITA = "w"

    TITULO_DO_GRAFICO_DA_FUNCAO_OBJETIVO = "Curva da função objetivo"
    TITULO_DO_GRAFICO_DA_NORMA_DO_GRADIENTE = "Evolução da norma do gradiente"
    TITULO_DO_GRAFICO_DA_ACURACIA = "Evolução da acurácia de treinamento"

    TEXTO_DO_EIXO_DAS_ITERACOES = "Iteração"
    TEXTO_DO_EIXO_DA_FUNCAO_OBJETIVO = "Função objetivo"
    TEXTO_DO_EIXO_DA_NORMA_DO_GRADIENTE = "Norma do gradiente"
    TEXTO_DO_EIXO_DA_ACURACIA = "Acurácia"

    MOTIVO_DA_PARADA_POR_NORMA_DO_GRADIENTE = "Norma do gradiente menor ou igual à tolerância."
    MOTIVO_DA_PARADA_POR_VARIACAO_DA_FUNCAO_OBJETIVO = "Variação da função objetivo menor ou igual à tolerância."
    MOTIVO_DA_PARADA_POR_NUMERO_MAXIMO_DE_ITERACOES = "Número máximo de iterações atingido."

    MENSAGEM_DE_ERRO_DE_PROCESSAMENTO = "Não foi possível processar os arquivos."
    MENSAGEM_DE_ERRO_DO_EXERCICIO_1 = "Não foi possível executar o Exercício 1."
    MENSAGEM_DE_SUCESSO_DO_EXERCICIO_1 = "Exercício 1 executado com sucesso."